version: '3.9'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  # App Database (Postgres for Prisma/Node)
  postgres:
    image: postgres:15
    container_name: codeflow-postgres
    restart: always
    environment:
      POSTGRES_USER: codeflow
      POSTGRES_PASSWORD: codeflow123
      POSTGRES_DB: codeflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codeflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeflow -d codeflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching, sessions, queues, etc.)
  redis:
    image: redis:7.2.4
    container_name: codeflow-redis
    command: >
      redis-server --appendonly no --requirepass redis_testing@123
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - codeflow-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_testing@123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  codeflow-network:
    driver: bridge
